version: "3"
services:

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: wiki
      MYSQL_ROOT_PASSWORD: wikijsrocks
      MYSQL_USER: wikijs
      MYSQL_PASSWORD: wikijsrocks
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "80:3000"
      - "443:3443"

volumes:
  db-data: